### ISSUE TITLE
Re-org projects

### ISSUE THREAD

**Issue by zifnab06** [lineageos-infra/issues#12]
OEM-/PROJECT- projects were a neat idea, they're unmaintainable and a huge pain in the ass. 

Look at moving these to:

- Lineage-Unmaintained-Projects
  - lineage/google/desire (if exists, if not just project)
- Lineage15.1-Projects
  - lineage/lge/mako
- Lineage-14.1-Projects
  - lineage/samsung/hero

**Comment by fourkbomb** [comment]
Why do we want a 15.1/14.1 distinction?

**Comment by zifnab06** [comment]
I want to be able to lock down old branches when we release new things, we currently lack that ability. It also makes moving things into 'unmaintained' when a new version is released easier.
